default:
  image: 'node:lts-slim'
  before_script:
    - npm ci

cache:
  paths:
    - node_modules/

stages:
  - lint
  - build
  - pages

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build

pages:
  stage: pages
  script:
    - npm run build -- --base=/vissoft22/
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public